/*
 * Copyright 2025 The Go-Spring Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"go-spring.org/cloud/data"
)

// backend describes the persistence binding the generated code delegates to.
// It defaults to the GORM binding; another backend exposing the same Query*
// executors and a New[T, ID] constructor can be substituted via the -backend
// and -backend-alias flags.
type backend struct {
	Import string // import path, e.g. "go-spring.org/starter-data-gorm"
	Alias  string // package alias used in generated code, e.g. "gormdata"
}

// emit renders the whole generated file for one parsed input.
func emit(p *parsed, b backend) ([]byte, error) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by gs-data-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", p.Pkg)

	// Emit the fixed imports first and record their paths, then carry over the
	// source imports the signatures reference, skipping any already emitted so
	// e.g. the source's own "context" does not double up.
	seen := map[string]bool{"context": true, "gorm.io/gorm": true, b.Import: true}
	buf.WriteString("import (\n\t\"context\"\n\n\t\"gorm.io/gorm\"\n")
	fmt.Fprintf(&buf, "\t%s %q\n", b.Alias, b.Import)
	for _, imp := range p.Imports {
		if seen[importPath(imp)] {
			continue
		}
		fmt.Fprintf(&buf, "\t%s\n", imp)
	}
	buf.WriteString(")\n\n")

	for _, r := range p.Repos {
		emitRepo(&buf, r, b)
	}

	out, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("gs-data-gen: generated code did not format: %w", err)
	}
	return out, nil
}

func emitRepo(buf *bytes.Buffer, r repoSpec, b backend) {
	impl := lowerFirst(r.Iface) + "Impl"
	gen := fmt.Sprintf("%s.Repository[%s, %s]", b.Alias, r.Entity, r.ID)

	fmt.Fprintf(buf, "// %s is the generated %s backed by %s.\n", impl, r.Iface, b.Alias)
	fmt.Fprintf(buf, "type %s struct {\n\t*%s\n}\n\n", impl, gen)

	fmt.Fprintf(buf, "// New%s builds a %s backed by the persistence handle.\n", r.Iface, r.Iface)
	fmt.Fprintf(buf, "func New%s(db *gorm.DB) %s {\n", r.Iface, r.Iface)
	fmt.Fprintf(buf, "\treturn &%s{Repository: %s.New[%s, %s](db)}\n}\n\n", impl, b.Alias, r.Entity, r.ID)

	for _, m := range r.Methods {
		emitMethod(buf, impl, m)
	}
}

func emitMethod(buf *bytes.Buffer, impl string, m methodSpec) {
	var sig strings.Builder
	sig.WriteString("ctx context.Context")
	var names []string
	for _, p := range m.Params {
		fmt.Fprintf(&sig, ", %s %s", p.Name, p.Type)
		names = append(names, p.Name)
	}
	argList := ""
	if len(names) > 0 {
		argList = ", " + strings.Join(names, ", ")
	}

	fmt.Fprintf(buf, "func (r *%s) %s(%s) %s {\n", impl, m.Name, sig.String(), m.Results)
	buf.WriteString("\t" + body(m, argList) + "\n}\n\n")
}

// body picks the backend executor that matches the method's subject and return
// cardinality, mirroring how Spring Data routes a derived query by its parts.
func body(m methodSpec, argList string) string {
	call := func(fn string) string {
		return fmt.Sprintf("r.%s(ctx, %q%s)", fn, m.Name, argList)
	}
	switch m.subject {
	case data.SubjectCount:
		return "return " + call("QueryCount")
	case data.SubjectExists:
		return "return " + call("QueryExists")
	case data.SubjectDelete:
		if m.nResult <= 1 { // method returns error only
			return "_, err := " + call("QueryDelete") + "\n\treturn err"
		}
		return "return " + call("QueryDelete")
	default: // SubjectFind
		if m.slice {
			return "return " + call("QueryMany")
		}
		return "return " + call("QueryOne")
	}
}

// importPath extracts the quoted path from an import spec line such as
// `uuid "github.com/google/uuid"` or `"time"`.
func importPath(spec string) string {
	i := strings.IndexByte(spec, '"')
	j := strings.LastIndexByte(spec, '"')
	if i < 0 || j <= i {
		return spec
	}
	return spec[i+1 : j]
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
