/*
 * Copyright 2025 The Go-Spring Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package main

import (
	"go/token"
	"strings"
	"testing"
)

const sample = `package repo

import (
	"context"
	"time"

	"go-spring.org/cloud/data"
)

type User struct {
	ID    int64
	Email string
}

type UserRepository interface {
	data.CrudRepository[User, int64]

	FindByEmail(ctx context.Context, email string) (User, bool, error)
	FindByCreatedAtAfter(ctx context.Context, t time.Time) ([]User, error)
	CountByStatus(ctx context.Context, status string) (int64, error)
	ExistsByEmail(ctx context.Context, email string) (bool, error)
	DeleteByStatus(ctx context.Context, status string) (int64, error)
}
`

func generate(t *testing.T) string {
	t.Helper()
	fset := token.NewFileSet()
	p, err := parse(fset, []byte(sample), "sample.go")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(p.Repos) != 1 {
		t.Fatalf("repos = %d, want 1", len(p.Repos))
	}
	code, err := emit(p, backend{Import: "go-spring.org/starter-data-gorm", Alias: "gormdata"})
	if err != nil {
		t.Fatalf("emit: %v\n%s", err, code)
	}
	return string(code)
}

func TestParseModel(t *testing.T) {
	fset := token.NewFileSet()
	p, _ := parse(fset, []byte(sample), "sample.go")
	r := p.Repos[0]
	if r.Entity != "User" || r.ID != "int64" {
		t.Fatalf("entity/id = %q/%q", r.Entity, r.ID)
	}
	if len(r.Methods) != 5 {
		t.Fatalf("methods = %d, want 5", len(r.Methods))
	}
	// time import must be carried over (used by FindByCreatedAtAfter).
	if !contains(p.Imports, `"time"`) {
		t.Errorf("imports missing time: %v", p.Imports)
	}
}

func TestEmitRoutesExecutors(t *testing.T) {
	code := generate(t)
	wants := []string{
		"// Code generated by gs-data-gen. DO NOT EDIT.",
		"package repo",
		"type userRepositoryImpl struct",
		"*gormdata.Repository[User, int64]",
		"func NewUserRepository(db *gorm.DB) UserRepository",
		`r.QueryOne(ctx, "FindByEmail", a1)`,
		`r.QueryMany(ctx, "FindByCreatedAtAfter", a1)`,
		`r.QueryCount(ctx, "CountByStatus", a1)`,
		`r.QueryExists(ctx, "ExistsByEmail", a1)`,
		`r.QueryDelete(ctx, "DeleteByStatus", a1)`,
		`a1 time.Time`, // carried-over import type is used
	}
	for _, w := range wants {
		if !strings.Contains(code, w) {
			t.Errorf("generated code missing %q\n---\n%s", w, code)
		}
	}
}

func contains(ss []string, s string) bool {
	for _, x := range ss {
		if x == s {
			return true
		}
	}
	return false
}
