// Code generated by gs-data-gen. DO NOT EDIT.

package example

import (
	"context"

	gormdata "go-spring.org/starter-data-gorm"
	"gorm.io/gorm"
)

// orderRepositoryImpl is the generated OrderRepository backed by gormdata.
type orderRepositoryImpl struct {
	*gormdata.Repository[Order, int64]
}

// NewOrderRepository builds a OrderRepository backed by the persistence handle.
func NewOrderRepository(db *gorm.DB) OrderRepository {
	return &orderRepositoryImpl{Repository: gormdata.New[Order, int64](db)}
}

func (r *orderRepositoryImpl) FindByCustomer(ctx context.Context, a1 string) ([]Order, error) {
	return r.QueryMany(ctx, "FindByCustomer", a1)
}

func (r *orderRepositoryImpl) FindByStatusOrderByTotalDesc(ctx context.Context, a1 string) ([]Order, error) {
	return r.QueryMany(ctx, "FindByStatusOrderByTotalDesc", a1)
}

func (r *orderRepositoryImpl) CountByStatus(ctx context.Context, a1 string) (int64, error) {
	return r.QueryCount(ctx, "CountByStatus", a1)
}

func (r *orderRepositoryImpl) ExistsByCustomer(ctx context.Context, a1 string) (bool, error) {
	return r.QueryExists(ctx, "ExistsByCustomer", a1)
}

func (r *orderRepositoryImpl) DeleteByStatus(ctx context.Context, a1 string) (int64, error) {
	return r.QueryDelete(ctx, "DeleteByStatus", a1)
}
