// Code generated by gs-cache-gen. DO NOT EDIT.

package example

import (
	"context"

	cache "go-spring.org/cloud/cache"
)

// bookServiceCache decorates BookService with cache-aside behaviour.
type bookServiceCache struct {
	inner BookService
	c     *cache.Cache
}

// NewBookServiceCache wraps inner so its //cache: methods read and write c.
func NewBookServiceCache(inner BookService, c *cache.Cache) BookService {
	return &bookServiceCache{inner: inner, c: c}
}

func (d *bookServiceCache) FindBook(ctx context.Context, isbn string) (*Book, error) {
	key := cache.BuildKey("books", isbn)
	var out *Book
	if err := d.c.Get(ctx, key, &out); err == nil {
		return out, nil
	}
	out, err := d.inner.FindBook(ctx, isbn)
	if err != nil {
		return out, err
	}
	_ = d.c.Set(ctx, key, out, 0)
	return out, nil
}

func (d *bookServiceCache) SaveBook(ctx context.Context, isbn string, b *Book) (*Book, error) {
	key := cache.BuildKey("books", isbn)
	out, err := d.inner.SaveBook(ctx, isbn, b)
	if err == nil {
		_ = d.c.Set(ctx, key, out, 0)
	}
	return out, err
}

func (d *bookServiceCache) DeleteBook(ctx context.Context, isbn string) error {
	key := cache.BuildKey("books", isbn)
	r0 := d.inner.DeleteBook(ctx, isbn)
	_ = d.c.Delete(ctx, key)
	return r0
}
