// Code generated by gs-sched-gen. DO NOT EDIT.

package example

import (
	"time"

	scheduling "go-spring.org/cloud/scheduling"
)

// RegisterReportTasks schedules every //schedule: method of impl on s.
// Call it once during application startup; a job error aborts registration.
func RegisterReportTasks(s *scheduling.Scheduler, impl ReportTasks) error {
	{
		tr := scheduling.FixedRate(20*time.Millisecond, scheduling.WithInitialDelay(1*time.Millisecond))
		job, err := scheduling.NewJob("ReportTasks.Rollup", tr, impl.Rollup)
		if err != nil {
			return err
		}
		if _, err := s.Schedule(job); err != nil {
			return err
		}
	}
	return nil
}
