/*
 * Copyright 2025 The Go-Spring Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

const cachePkg = "go-spring.org/cloud/cache"

// emit renders the decorator file for one parsed input.
func emit(p *parsed) ([]byte, error) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by gs-cache-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", p.Pkg)

	seen := map[string]bool{"context": true, cachePkg: true}
	buf.WriteString("import (\n\t\"context\"\n")
	if p.usesTTL {
		buf.WriteString("\t\"time\"\n")
		seen["time"] = true
	}
	fmt.Fprintf(&buf, "\n\tcache %q\n", cachePkg)
	for _, imp := range p.Imports {
		if seen[importPath(imp)] {
			continue
		}
		fmt.Fprintf(&buf, "\t%s\n", imp)
	}
	buf.WriteString(")\n\n")

	for _, s := range p.Svcs {
		if err := emitSvc(&buf, s); err != nil {
			return nil, err
		}
	}

	out, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("gs-cache-gen: generated code did not format: %w", err)
	}
	return out, nil
}

func emitSvc(buf *bytes.Buffer, s svc) error {
	impl := lowerFirst(s.Iface) + "Cache"
	fmt.Fprintf(buf, "// %s decorates %s with cache-aside behaviour.\n", impl, s.Iface)
	fmt.Fprintf(buf, "type %s struct {\n\tinner %s\n\tc     *cache.Cache\n}\n\n", impl, s.Iface)
	fmt.Fprintf(buf, "// New%sCache wraps inner so its //cache: methods read and write c.\n", s.Iface)
	fmt.Fprintf(buf, "func New%sCache(inner %s, c *cache.Cache) %s {\n\treturn &%s{inner: inner, c: c}\n}\n\n", s.Iface, s.Iface, s.Iface, impl)
	for _, m := range s.Methods {
		if err := emitMethod(buf, impl, m); err != nil {
			return err
		}
	}
	return nil
}

func emitMethod(buf *bytes.Buffer, impl string, m method) error {
	var params []string
	var argNames []string
	for _, p := range m.Params {
		params = append(params, p.Name+" "+p.Type)
		argNames = append(argNames, p.Name)
	}
	results := ""
	if len(m.Results) == 1 {
		results = m.Results[0]
	} else if len(m.Results) > 1 {
		results = "(" + strings.Join(m.Results, ", ") + ")"
	}
	fmt.Fprintf(buf, "func (d *%s) %s(%s) %s {\n", impl, m.Name, strings.Join(params, ", "), results)

	b, err := body(m, argNames)
	if err != nil {
		return fmt.Errorf("%s: %w", m.Name, err)
	}
	buf.WriteString(b + "\n}\n\n")
	return nil
}

// body renders the method implementation for its caching kind.
func body(m method, argNames []string) (string, error) {
	ctx := argNames[0]
	call := fmt.Sprintf("d.inner.%s(%s)", m.Name, strings.Join(argNames, ", "))

	if !m.hasDir {
		if len(m.Results) == 0 {
			return "\t" + call, nil
		}
		return "\treturn " + call, nil
	}

	key := keyExpr(m, argNames)
	switch m.dir.kind {
	case cacheable, put:
		if len(m.Results) != 2 || m.Results[1] != "error" {
			return "", fmt.Errorf("cacheable/put requires a (T, error) return, got %v", m.Results)
		}
		if m.dir.kind == cacheable {
			return fmt.Sprintf("\tkey := %s\n\tvar out %s\n\tif err := d.c.Get(%s, key, &out); err == nil {\n\t\treturn out, nil\n\t}\n\tout, err := %s\n\tif err != nil {\n\t\treturn out, err\n\t}\n\t_ = d.c.Set(%s, key, out, %s)\n\treturn out, nil",
				key, m.Results[0], ctx, call, ctx, m.dir.ttl), nil
		}
		return fmt.Sprintf("\tkey := %s\n\tout, err := %s\n\tif err == nil {\n\t\t_ = d.c.Set(%s, key, out, %s)\n\t}\n\treturn out, err",
			key, call, ctx, m.dir.ttl), nil
	default: // evict
		if len(m.Results) == 0 {
			return fmt.Sprintf("\tkey := %s\n\t%s\n\t_ = d.c.Delete(%s, key)", key, call, ctx), nil
		}
		var rs []string
		for i := range m.Results {
			rs = append(rs, fmt.Sprintf("r%d", i))
		}
		joined := strings.Join(rs, ", ")
		return fmt.Sprintf("\tkey := %s\n\t%s := %s\n\t_ = d.c.Delete(%s, key)\n\treturn %s", key, joined, call, ctx, joined), nil
	}
}

// keyExpr builds the cache.BuildKey call: the named key params, or (default)
// every argument after the context, or the bare name for evict all.
func keyExpr(m method, argNames []string) string {
	parts := m.dir.key
	if m.dir.kind == evict && m.dir.all {
		parts = nil
	} else if len(parts) == 0 {
		parts = argNames[1:] // skip ctx
	}
	if len(parts) == 0 {
		return fmt.Sprintf("cache.BuildKey(%q)", m.dir.name)
	}
	return fmt.Sprintf("cache.BuildKey(%q, %s)", m.dir.name, strings.Join(parts, ", "))
}

func importPath(spec string) string {
	i := strings.IndexByte(spec, '"')
	j := strings.LastIndexByte(spec, '"')
	if i < 0 || j <= i {
		return spec
	}
	return spec[i+1 : j]
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
