/*
 * Copyright 2025 The Go-Spring Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package main

import (
	"go/token"
	"strings"
	"testing"
)

const sample = `package svc

import "context"

type Book struct {
	ISBN  string
	Title string
}

type BookService interface {
	//cache:cacheable name=books key=isbn ttl=5m
	FindBook(ctx context.Context, isbn string) (*Book, error)

	//cache:put name=books key=isbn
	SaveBook(ctx context.Context, isbn string, b *Book) (*Book, error)

	//cache:evict name=books key=isbn
	DeleteBook(ctx context.Context, isbn string) error

	// Plain pass-through, no caching.
	Count(ctx context.Context) (int, error)
}
`

func gen(t *testing.T) string {
	t.Helper()
	fset := token.NewFileSet()
	p, err := parse(fset, []byte(sample), "sample.go")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(p.Svcs) != 1 || len(p.Svcs[0].Methods) != 4 {
		t.Fatalf("svcs = %+v", p.Svcs)
	}
	code, err := emit(p)
	if err != nil {
		t.Fatalf("emit: %v\n%s", err, code)
	}
	return string(code)
}

func TestEmitCaching(t *testing.T) {
	code := gen(t)
	wants := []string{
		"// Code generated by gs-cache-gen. DO NOT EDIT.",
		`"time"`, // ttl=5m pulls in time
		"func NewBookServiceCache(inner BookService, c *cache.Cache) BookService",
		`key := cache.BuildKey("books", isbn)`,
		"if err := d.c.Get(ctx, key, &out); err == nil {",
		"_ = d.c.Set(ctx, key, out, 5*time.Minute)",  // cacheable with ttl (gofmt-normalized)
		"out, err := d.inner.SaveBook(ctx, isbn, b)", // put calls inner
		"_ = d.c.Delete(ctx, key)",                   // evict
		"return d.inner.Count(ctx)",                  // pass-through
	}
	for _, w := range wants {
		if !strings.Contains(code, w) {
			t.Errorf("missing %q\n---\n%s", w, code)
		}
	}
}

func TestPutHasNoTTLImportWhenUnset(t *testing.T) {
	src := `package svc

import "context"

type S interface {
	//cache:evict name=x key=id
	Del(ctx context.Context, id string) error
}
`
	fset := token.NewFileSet()
	p, _ := parse(fset, []byte(src), "s.go")
	code, err := emit(p)
	if err != nil {
		t.Fatalf("emit: %v", err)
	}
	if strings.Contains(string(code), `"time"`) {
		t.Errorf("time imported though no ttl used:\n%s", code)
	}
}
