/*
 * Copyright 2025 The Go-Spring Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

const schedPkg = "go-spring.org/cloud/scheduling"

// emit renders the registration file for one parsed input. For each cached
// interface it writes Register<Iface>(s *scheduling.Scheduler, impl <Iface>)
// error, which builds a job per //schedule: method and schedules it.
func emit(p *parsed) ([]byte, error) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by gs-sched-gen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", p.Pkg)

	buf.WriteString("import (\n")
	if p.usesTime {
		buf.WriteString("\t\"time\"\n\n")
	}
	fmt.Fprintf(&buf, "\tscheduling %q\n)\n\n", schedPkg)

	for _, s := range p.Svcs {
		emitSvc(&buf, s)
	}

	out, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("gs-sched-gen: generated code did not format: %w", err)
	}
	return out, nil
}

func emitSvc(buf *bytes.Buffer, s svc) {
	fmt.Fprintf(buf, "// Register%s schedules every //schedule: method of impl on s.\n", s.Iface)
	fmt.Fprintf(buf, "// Call it once during application startup; a job error aborts registration.\n")
	fmt.Fprintf(buf, "func Register%s(s *scheduling.Scheduler, impl %s) error {\n", s.Iface, s.Iface)
	for _, j := range s.Jobs {
		emitJob(buf, s.Iface, j)
	}
	buf.WriteString("\treturn nil\n}\n\n")
}

func emitJob(buf *bytes.Buffer, iface string, j job) {
	name := j.sc.name
	if name == "" {
		name = iface + "." + j.Method
	}
	buf.WriteString("\t{\n")

	// Trigger construction: cron returns an error; fixed* do not.
	switch j.sc.kind {
	case "cron":
		fmt.Fprintf(buf, "\t\ttr, err := scheduling.ParseCron(%q)\n\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n", j.sc.cron)
	default: // fixedRate / fixedDelay -> FixedRate / FixedDelay
		fn := strings.ToUpper(j.sc.kind[:1]) + j.sc.kind[1:]
		fmt.Fprintf(buf, "\t\ttr := scheduling.%s(%s%s)\n", fn, j.sc.rate, triggerOpts(j.sc))
	}

	fmt.Fprintf(buf, "\t\tjob, err := scheduling.NewJob(%q, tr, impl.%s%s)\n", name, j.Method, jobOpts(j.sc))
	buf.WriteString("\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n")
	buf.WriteString("\t\tif _, err := s.Schedule(job); err != nil {\n\t\t\treturn err\n\t\t}\n")
	buf.WriteString("\t}\n")
}

// triggerOpts renders the variadic TriggerOptions for a fixed* trigger.
func triggerOpts(sc schedule) string {
	var s string
	if sc.initialDelay != "" {
		s += fmt.Sprintf(", scheduling.WithInitialDelay(%s)", sc.initialDelay)
	}
	if sc.jitter != "" {
		s += fmt.Sprintf(", scheduling.WithJitter(%s)", sc.jitter)
	}
	return s
}

// jobOpts renders the variadic job Options.
func jobOpts(sc schedule) string {
	if sc.timeout != "" {
		return fmt.Sprintf(", scheduling.WithTimeout(%s)", sc.timeout)
	}
	return ""
}
