/*
 * Copyright 2025 The Go-Spring Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package main

import (
	"go/token"
	"strings"
	"testing"
)

const sample = `package tasks

import "context"

type ReportTasks interface {
	//schedule:fixedRate=5s initialDelay=1s timeout=10s
	Rollup(ctx context.Context) error

	//schedule:fixedDelay=30s
	Compact(ctx context.Context) error

	//schedule:cron="0 0 * * *" name=nightly
	Nightly(ctx context.Context) error

	// Not scheduled.
	Helper(ctx context.Context) error
}
`

func gen(t *testing.T) string {
	t.Helper()
	fset := token.NewFileSet()
	p, err := parse(fset, []byte(sample), "s.go")
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(p.Svcs) != 1 || len(p.Svcs[0].Jobs) != 3 {
		t.Fatalf("svcs = %+v", p.Svcs)
	}
	code, err := emit(p)
	if err != nil {
		t.Fatalf("emit: %v\n%s", err, code)
	}
	return string(code)
}

func TestEmitSchedule(t *testing.T) {
	code := gen(t)
	wants := []string{
		"// Code generated by gs-sched-gen. DO NOT EDIT.",
		`"time"`,
		"func RegisterReportTasks(s *scheduling.Scheduler, impl ReportTasks) error",
		"tr := scheduling.FixedRate(5*time.Second, scheduling.WithInitialDelay(1*time.Second))",
		`scheduling.NewJob("ReportTasks.Rollup", tr, impl.Rollup, scheduling.WithTimeout(10*time.Second))`,
		"tr := scheduling.FixedDelay(30*time.Second)",
		`tr, err := scheduling.ParseCron("0 0 * * *")`,
		`scheduling.NewJob("nightly", tr, impl.Nightly)`, // name override
		"s.Schedule(job)",
	}
	// Compare with whitespace removed: gofmt's spacing around operators (e.g.
	// "5*time.Second" vs "5 * time.Second") is not something the test should pin.
	stripped := strings.ReplaceAll(code, " ", "")
	for _, w := range wants {
		if !strings.Contains(stripped, strings.ReplaceAll(w, " ", "")) {
			t.Errorf("missing %q\n---\n%s", w, code)
		}
	}
	if strings.Contains(code, "impl.Helper") {
		t.Error("unscheduled method should not be registered")
	}
}

func TestBadSignatureRejected(t *testing.T) {
	src := `package t

import "context"

type S interface {
	//schedule:fixedRate=5s
	Bad(ctx context.Context, x int) error
}
`
	fset := token.NewFileSet()
	if _, err := parse(fset, []byte(src), "s.go"); err == nil {
		t.Fatal("expected signature rejection")
	}
}
